# Generated by Django 6.0.3 on 2026-05-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_researcher_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='research_interests',
        ),
    ]
